# def2gds.tcl - Convert OpenROAD DEF output to GDSII using Magic


# 1. Load the technology file (implicitly loaded when starting magic with -T sky130A)
#    No explicit command needed here if sky130A is loaded by default.


# 2. Read the LEF files that define the layers and macro abstractions
lef read /openlane/pdks/<CIEL_VERSION>/sky130A/libs.ref/sky130_fd_sc_hd/techlef/sky130_fd_sc_hd__nom.tlef
lef read /openlane/pdks/<CIEL_VERSION>/sky130A/libs.ref/sky130_fd_sc_hd/lef/sky130_fd_sc_hd.lef


# 3. Read the standard cell GDS which contains the physical geometries
gds read /openlane/pdks/<CIEL_VERSION>/sky130A/libs.ref/sky130_fd_sc_hd/gds/sky130_fd_sc_hd.gds


# 4. Read your DEF file generated by OpenROAD
def read ./mini_cpu.def


# 5. Select the top-level cell to be processed
load mini_cpu_top


# 6. Write the final merged layout to a GDSII file
gds write ./mini_cpu.gds


puts "GDS file written: mini_cpu.gds"
exit
